/* Generated By:JavaCC: Do not edit this line. PropParserConstants.java */
package org.net9.simplex.ppmc.prop.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PropParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int DELIM = 2;
  /** RegularExpression Id. */
  int NOT = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int PROB = 8;
  /** RegularExpression Id. */
  int NEXT = 9;
  /** RegularExpression Id. */
  int EVENTUALLY = 10;
  /** RegularExpression Id. */
  int ALWAYS = 11;
  /** RegularExpression Id. */
  int UNTIL = 12;
  /** RegularExpression Id. */
  int COMP = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int FLOAT = 16;
  /** RegularExpression Id. */
  int IDENT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<DELIM>",
    "\"!\"",
    "<AND>",
    "<OR>",
    "\"true\"",
    "\"false\"",
    "\"P\"",
    "\"X\"",
    "\"<>\"",
    "\"[]\"",
    "\"U\"",
    "<COMP>",
    "<DIGIT>",
    "<INTEGER>",
    "<FLOAT>",
    "<IDENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
  };

}
